ovirt:
  username: admin@internal
  ca_file: /etc/pki/ovirt-engine/ca.pem
  password: redhat
  data_center: Default
  cluster: Default
  host: rhevm.lan
  storage:
     interface: virtio
     storage_domain: rhevdata
  network:
    external:
       interface: virtio
       profile: vlan19
       network: vlan19
    internal:
       interface: virtio
       profile: vlan22Test
       network: vlan22Test
       host_interface: eno2

engine_password: redhat
engine_fqdn: "{{ inventory_hostname }}"
engine_user: admin@internal
engine_cafile: /etc/pki/ovirt-engine/ca.pem
ovirt_engine_ssh_user: admin
